version: "3.4"

services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
